---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30005
  selector:
    app: gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  annotations:
    kubernetes.io/change-cause: "mkubik/gateway:latest"
spec:
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: mkubik/gateway:latest
        env:
        - name: VCAP_APP_PORT
          value: "5000"
        - name: CART_ENTRYPOINT
          #value: "http://cart-service.default.svc.cluster.local:5002"
          value: "http://cart-service:5002"
        - name: CAT_ENTRYPOINT
          #value: "http://cat-service.default.svc.cluster.local:5001"
          value: "http://cat-service:5001"
        - name: SHIP_ENTRYPOINT
          #value: "http://ship-service.default.svc.cluster.local:5001"
          value: "${SHIP_ENDPOINT}"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: image-repo-secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: gateway
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
