---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  type: NodePort
  ports:
  - port: 8043
    protocol: TCP
    targetPort: 8043
    nodePort: 30000
  selector:
    app: website
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
  annotations:
    kubernetes.io/change-cause: "mkubik/website:latest"
spec:
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: mkubik/website:latest
        env:
        - name: GATEWAY_ENDPOINT
          value: "http://gateway-service:30005"
        ports:
        - containerPort: 8043
        resources:
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: image-repo-secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: website
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: website
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
